<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Introduction to Medical Statistics with Jamovi - 1&nbsp; Introduction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./lab1.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="site_libs/htmlwidgets-1.5.4/htmlwidgets.js"></script><link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="site_libs/datatables-binding-0.23/datatables.js"></script><script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><link href="site_libs/dt-core-1.11.3/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="site_libs/dt-core-1.11.3/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="site_libs/dt-core-1.11.3/js/jquery.dataTables.min.js"></script><link href="site_libs/dt-ext-scroller-1.11.3/css/scroller.dataTables.min.css" rel="stylesheet">
<script src="site_libs/dt-ext-scroller-1.11.3/js/dataTables.scroller.min.js"></script><link href="site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script><script src="site_libs/quarto-diagram/mermaid.min.js"></script><script src="site_libs/quarto-diagram/mermaid-init.js"></script><link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Medical Statistics with Jamovi</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/bougioukas/MedStatsJamovi5" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Share" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-share"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
<li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
            <i class="bi bi-bi-twitter pe-1"></i>
          Twitter
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
            <i class="bi bi-bi-facebook pe-1"></i>
          Facebook
          </a>
        </li>
    </ul>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">LAB I: Introduction to Jamovi (Part I)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./study_designs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sampling methods and study designs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">LAB II: Introduction to Jamovi (Part II)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probability and distributions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">LAB III: Probability and distributions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Normal distribution</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab4.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">LAB IV: Normal distribution</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Foundations for statistical inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab5.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">LAB V: Foundations for inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two_samples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Inference for numerical data: 2 samples</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab6.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">LAB VI: Inference for numerical data (2 samples)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more_samples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference for numerical data: &gt;2 samples</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab7.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">LAB VII: Inference for numerical data (&gt;2 samples)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./categorical.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Inference for categorical data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab8.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">LAB VIII: Inference for categorical data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Correlation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab9.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">LAB IX: Correlation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Simple linear regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab10.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">LAB X: Simple linear regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Reporting the results of statistical analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#statistics-and-medicine" id="toc-statistics-and-medicine" class="nav-link active" data-scroll-target="#statistics-and-medicine"> <span class="header-section-number">1.1</span> Statistics and Medicine</a></li>
  <li><a href="#why-jamovi" id="toc-why-jamovi" class="nav-link" data-scroll-target="#why-jamovi"> <span class="header-section-number">1.2</span> Why Jamovi?</a></li>
  <li>
<a href="#types-of-data" id="toc-types-of-data" class="nav-link" data-scroll-target="#types-of-data"> <span class="header-section-number">1.3</span> Types of Data</a>
  <ul class="collapse">
<li><a href="#categorical-data" id="toc-categorical-data" class="nav-link" data-scroll-target="#categorical-data">Categorical Data</a></li>
  <li><a href="#numerical-data" id="toc-numerical-data" class="nav-link" data-scroll-target="#numerical-data">Numerical Data</a></li>
  </ul>
</li>
  <li><a href="#summarizing-categorical-data" id="toc-summarizing-categorical-data" class="nav-link" data-scroll-target="#summarizing-categorical-data"> <span class="header-section-number">1.4</span> Summarizing Categorical Data</a></li>
  <li><a href="#displaying-categorical-data" id="toc-displaying-categorical-data" class="nav-link" data-scroll-target="#displaying-categorical-data"> <span class="header-section-number">1.5</span> Displaying Categorical Data</a></li>
  <li>
<a href="#summarizing-numerical-data" id="toc-summarizing-numerical-data" class="nav-link" data-scroll-target="#summarizing-numerical-data"> <span class="header-section-number">1.6</span> Summarizing Numerical Data</a>
  <ul class="collapse">
<li><a href="#measures-of-location" id="toc-measures-of-location" class="nav-link" data-scroll-target="#measures-of-location">Measures of Location</a></li>
  <li><a href="#measures-of-dispersion" id="toc-measures-of-dispersion" class="nav-link" data-scroll-target="#measures-of-dispersion">Measures of Dispersion</a></li>
  </ul>
</li>
  <li><a href="#displaying-numerical-data" id="toc-displaying-numerical-data" class="nav-link" data-scroll-target="#displaying-numerical-data"> <span class="header-section-number">1.7</span> Displaying Numerical Data</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"> <span class="header-section-number">1.8</span> Exercises</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-introduction" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="cell page-columns page-full" data-fig-width="9">
<div class="cell-output-display column-screen-inset-right">
<div>
<p>
</p>
<pre class="mermaid" data-tooltip-selector="#mermaid-tooltip-1">flowchart LR
Q[Research<br>Question] --&gt; M[Measurements] --&gt; D[Design] --&gt; Ac[Data<br>Acquisition] --&gt; Des[Description] --&gt; A[Analysis] --&gt; I[Interpretation] &amp; Pred[Prediction]
Pred --&gt; V[Validation]
I --&gt; K[New Knowledge] &amp; Dec[Decision<br>Making]
</pre>
<div id="mermaid-tooltip-1" class="mermaidTooltip">

</div>

</div>
</div>
</div>
<section id="statistics-and-medicine" class="level2" data-number="1.1"><h2 data-number="1.1" class="anchored" data-anchor-id="statistics-and-medicine">
<span class="header-section-number">1.1</span> Statistics and Medicine</h2>
<p>Although some healthcare professionals may not carry out medical research, they will definitely be consumers of medical research. Thus, it is incumbent on them to be able to discern high quality research studies from low quality, to be able to verify whether the conclusions of a study are valid and to understand the limitations in methods of a study. The current emphasis on evidence-based medicine (EBM) requires that healthcare professionals consider critically all evidence about whether a specific treatment works and this requires basic statistical knowledge.</p>
<p>Statistics is not only a discipline in its own right but it is also a fundamental tool for investigation in all biological and medical sciences. As such, any serious investigator in these fields must have a grasp of the basic principles. With modern computer facilities there is little need for familiarity with the technical details of statistical calculations. However, a healthcare professional should understand when such calculations are valid, when they are not and how they should be interpreted.</p>
<p>The use of statistical methods pervades the medical literature. In a survey of 350 original articles published in three UK journals of general practice: <em>British Medical Journal (General Practice Section)</em>, <em>British Journal of General Practice</em> and <em>Family Practice</em>, over a one-year period, Rigby et al.&nbsp;(2004) found that 66% used some form of statistical analysis. Another review by Strasak et al.&nbsp;(2007) of 91 original research articles published in <em>The New England Journal of Medicine</em> (one of the prestigious peer-reviewed medical journals) found an even higher percentage (95%) of using inferential statistics, for example, hypothesis testing and deriving estimates. It appears, therefore, that the majority of papers published in these journals require some statistical knowledge for a complete understanding.</p>
<p>To students schooled in the ‘hard’ sciences of physics and chemistry it may be difficult to appreciate the variability of biological data. If one repeatedly puts blue litmus paper into acid solutions it turns red 100% of the time, not most (say 95%) of the time. In contrast, if one gives aspirin to a group of people with headaches, not all of them will experience relief. Penicillin was perhaps one of the few ‘miracle’ cures where the results were so dramatic that little evaluation was required. Absolute certainty in medicine is rare.</p>
<p>Measurements on human subjects seldom give exactly the same results from one occasion to the next. For example, O’ Sullivan et al (1999), found that systolic blood pressure (SBP) in normal healthy children has a wide range, with 95% of children having SBPs below 130 mmHg when they were resting, rising to 160 mmHg during the school day, and falling again to below 130 mmHg at night. Furthermore, Hansen et al.&nbsp;(2010) in a study of over 8000 subjects found that increasing variability in blood pressure over 24 hours was a significant and independent predictor of mortality and a cardiovascular and stroke events.</p>
<p>This variability is also inherent in responses to biological hazards. Most people now accept that cigarette smoking causes lung cancer and heart disease, and yet nearly everyone can point to an apparently healthy 80-year-old who has smoked for many years without apparent ill effect. Although it is now known from the report of Doll et al (2004) that about half of all persistent cigarette smokers are killed by their habit, it is usually forgotten that until the 1950s, the cause of the rise in lung cancer deaths was a mystery and commonly associated with general atmospheric pollution such as the exhaust fumes of cars. It was not until the carefully designed and statistically analysed case–control and cohort studies of Richard Doll and Austin Bradford Hill and others, that smoking was identified as the true cause. Enstrom et al.&nbsp;(2003) moved the debate on to ask whether or not passive smoking causes lung cancer. This is a more difficult question to answer since the association is weaker. However, studies by Cao et al.&nbsp;(2015) have now shown that it is a major health problem and scientists at the International Agency for Rsearch on Cancer (IARC) have concluded that there is sufficient evidence that second-hand smoke causes lung cancer (IARC 2012). Restrictions on smoking in public places have been imposed to smokers.</p>
<p>With such variability, it follows that in any comparison made in a medical context, such as people on different treatments, differences are almost bound to occur. These differences may be due to real effects, random variation or variation in some other factor that may affect an outcome. It is the job of the analyst to decide how much variation should be ascribed to chance or other factors, so that any remaining variation can be assumed to be due to a real effect. This is the art of statistics.</p>
</section><section id="why-jamovi" class="level2" data-number="1.2"><h2 data-number="1.2" class="anchored" data-anchor-id="why-jamovi">
<span class="header-section-number">1.2</span> Why Jamovi?</h2>
<p>Jamovi is a new fee open “3rd generation” statistical software that is built on top of the programming language R (<a href="#fig-jamovi_0">Figure&nbsp;<span>1.1</span></a>). Designed from the ground up to be easy to use, Jamovi is a compelling alternative to costly statistical products such as SPSS and SAS.</p>
<div id="fig-jamovi_0" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/jamovi_0.png" class="img-fluid figure-img" style="width:95.0%"></p>
<p></p><figcaption class="figure-caption">Figure 1.1: Jamovi is free and open statistical software</figcaption><p></p>
</figure>
</div>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<strong>Some other advantages are:</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Enables integration with R</li>
<li>It provides informative tables and neat visuals</li>
<li>Gives access to a user guide and community resources from the Jamovi website</li>
</ol>
</div>
</div>
</section><section id="types-of-data" class="level2" data-number="1.3"><h2 data-number="1.3" class="anchored" data-anchor-id="types-of-data">
<span class="header-section-number">1.3</span> Types of Data</h2>
<p>Data can be either categorical or numerical (otherwise known as qualitative and quantitative) in nature (<a href="#fig-types_data">Figure&nbsp;<span>1.2</span></a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-types_data" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/types_data.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 1.2: Broad classification of the different types of data with examples</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<strong>Example from the literature - Salicylic acid plasters for treatment of foot corns</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a randomized controlled trial (RCT), <span class="citation" data-cites="farndon2013">Farndon et al. (<a href="references.html#ref-farndon2013" role="doc-biblioref">2013</a>)</span> investigated the effectiveness of salicylic acid plasters compared with usual scalpel debridement for treatment of foot corns. The recorded data is as follows:</p>
<div class="cell">
<div class="cell-output-display">

<div id="htmlwidget-12cae066db9adfc7db2b" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-12cae066db9adfc7db2b">{"x":{"filter":"none","vertical":false,"extensions":["Scroller"],"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156","157","158","159","160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180","181","182","183","184","185","186","187","188","189","190","191","192","193","194","195","196","197","198","199","200","201","202"],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202],["corn plaster","corn plaster","corn plaster","corn plaster","scalpel","scalpel","scalpel","scalpel","scalpel","scalpel","scalpel","scalpel","scalpel","scalpel","scalpel","scalpel","corn plaster","scalpel","scalpel","scalpel","corn plaster","scalpel","scalpel","scalpel","scalpel","scalpel","corn plaster","corn plaster","scalpel","scalpel","scalpel","scalpel","corn plaster","corn plaster","scalpel","corn plaster","corn plaster","scalpel","corn plaster","scalpel","corn plaster","corn plaster","scalpel","corn plaster","scalpel","scalpel","corn plaster","corn plaster","scalpel","corn plaster","scalpel","scalpel","corn plaster","corn plaster","scalpel","scalpel","corn plaster","scalpel","corn plaster","scalpel","corn plaster","scalpel","scalpel","scalpel","scalpel","corn plaster","scalpel","scalpel","corn plaster","corn plaster","scalpel","corn plaster","corn plaster","corn plaster","corn plaster","scalpel","scalpel","corn plaster","scalpel","scalpel","scalpel","scalpel","scalpel","scalpel","scalpel","corn plaster","corn plaster","corn plaster","scalpel","scalpel","corn plaster","scalpel","corn plaster","scalpel","scalpel","corn plaster","corn plaster","scalpel","corn plaster","corn plaster","scalpel","corn plaster","corn plaster","scalpel","corn plaster","scalpel","scalpel","corn plaster","scalpel","scalpel","corn plaster","scalpel","corn plaster","corn plaster","corn plaster","corn plaster","corn plaster","corn plaster","scalpel","corn plaster","scalpel","corn plaster","corn plaster","scalpel","corn plaster","corn plaster","scalpel","scalpel","corn plaster","corn plaster","corn plaster","corn plaster","corn plaster","scalpel","corn plaster","corn plaster","corn plaster","scalpel","corn plaster","corn plaster","corn plaster","scalpel","corn plaster","scalpel","corn plaster","scalpel","scalpel","corn plaster","corn plaster","corn plaster","corn plaster","scalpel","scalpel","scalpel","scalpel","scalpel","scalpel","scalpel","corn plaster","scalpel","scalpel","scalpel","corn plaster","scalpel","corn plaster","scalpel","corn plaster","corn plaster","scalpel","corn plaster","corn plaster","corn plaster","corn plaster","corn plaster","scalpel","scalpel","corn plaster","corn plaster","corn plaster","corn plaster","corn plaster","scalpel","scalpel","corn plaster","corn plaster","corn plaster","corn plaster","scalpel","scalpel","scalpel","corn plaster","scalpel","corn plaster","corn plaster","scalpel","corn plaster","scalpel","corn plaster","corn plaster","corn plaster","corn plaster","scalpel"],["Central","Huddersfield","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","First Park","First Park","First Park","First Park","First Park","First Park","First Park","First Park","First Park","First Park","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Darnall","Limbrick","Limbrick","Limbrick","Huddersfield","Huddersfield","Huddersfield","Huddersfield","Huddersfield","Huddersfield","Huddersfield","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","First Park","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Manor","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Darnall","Limbrick","Limbrick","Limbrick","Limbrick","Limbrick","Darnall","Huddersfield","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Central","Manor","Manor","Manor","Manor","Manor","Central","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Jordanthorpe","Darnall","Limbrick","Darnall","Darnall"],["female","female","male","female","female","female","female","male","female","male","female","male","male","female","female","male","female","male","female","male","female","male","male","female","male","female","male","female","male","female","male","female","male","female","female","male","male","female","female","female","female","male","male","female","female","male","male","male","female","male","male","male","female","female","female","female","female","female","female","female","female","male","male","female","female","male","female","female","male","male","male","female","female","female","female","female","male","male","female","female","female","male","female","male","female","male","male","female","female","female","male","female","female","male","female","female","male","male","female","female","female","male","female","male","male","female","female","male","male","female","male","female","male","male","female","male","male","male","male","female","male","male","female","male","female","female","male","female","female","female","female","male","male","male","female","male","female","female","female","female","female","female","female","female","male","male","female","female","female","female","female","male","male","male","female","female","male","female","female","female","male","female","female","female","female","female","male","male","female","female","female","male","male","female","female","female","female","female","female","male","female","female","male","male","female","male","female","female","female","male","female","male","female","female","female","female","male","male","male","male","male","male"],[1,null,3,2,1,1,1,1,1,2,1,1,3,1,3,3,3,1,2,null,2,1,3,3,2,3,1,1,2,3,1,1,3,3,3,1,2,3,2,3,2,3,3,1,3,3,1,1,2,2,1,1,3,2,3,1,3,1,3,1,1,3,3,1,3,2,2,1,1,3,1,3,3,1,3,1,2,1,1,3,1,3,1,1,1,null,2,3,1,2,2,1,1,3,1,3,null,3,1,1,2,2,3,1,2,3,3,3,2,1,1,3,1,1,2,3,1,1,3,1,3,1,3,2,1,3,null,2,3,1,1,2,1,3,3,1,3,1,3,3,3,3,1,3,3,3,3,2,1,2,1,3,2,3,1,1,3,1,1,3,2,3,3,3,2,1,3,3,2,1,3,2,3,2,3,3,3,2,3,3,2,3,2,1,1,3,2,3,3,1,3,1,3,3,1,1,1,3,3,3,3,3],[1,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3],[77,32,39,76,69,79,70,64,73,65,33,67,36,77,30,19,66,43,79,50,44,59,63,76,77,60,55,70,80,40,50,78,43,70,44,83,69,66,65,32,90,40,36,69,37,56,53,49,42,74,76,60,69,34,38,49,57,70,45,65,36,42,64,52,65,70,45,51,41,60,65,55,60,61,57,88,69,67,89,81,76,86,69,45,42,20,88,29,84,73,27,63,64,70,83,52,31,60,58,61,77,50,73,53,84,52,68,63,54,27,64,73,46,76,61,62,63,65,65,35,78,71,55,61,71,44,39,78,73,33,61,79,72,29,61,45,35,45,47,32,46,34,86,31,59,55,52,71,70,78,80,32,69,63,52,80,73,86,65,19,74,70,44,46,85,54,40,69,85,49,49,68,44,71,47,40,68,52,42,60,76,49,84,54,70,45,68,65,33,79,68,82,75,49,76,82,68,45,47,49,62,63],[1.100000024,null,5.300000191,7.599999905,1.399999976,4.599999905,9,4.599999905,2.400000095,3.299999952,7,0.699999988,2,1,4,6,1,7.599999905,7.800000191,1.5,3.599999905,0.100000001,5.400000095,8.800000191,8.5,5,1,8.800000191,3.299999952,6.199999809,5,2.5,1.600000024,6,9.800000191,9.5,2,5.400000095,2,7.5,4.5,2.400000095,5,3.200000048,8.5,6,0.400000006,3.299999952,1.399999976,1.5,0,0.100000001,1,5,3.700000048,5.400000095,1.899999976,5.400000095,7.400000095,6.699999809,9.399999619,7,1,4,8,7.900000095,3,6.199999809,0.5,8.5,0,7.599999905,2.5,3.400000095,6.5,2.700000048,8.600000381,8.699999809,4.099999905,7,0.600000024,1.200000048,4.900000095,10,3.799999952,2.400000095,7.400000095,4.5,0,9.100000381,10,4.5,6.599999905,2.400000095,9.5,5,3.400000095,5.199999809,9.600000381,6,4.699999809,7.300000191,7.5,0,4.5,1.200000048,7.199999809,3,0,0,3.099999905,8.899999619,2.5,0.400000006,6.199999809,7.300000191,4.800000191,7.5,2.5,4,2.5,2,5.599999905,6.599999905,5,8,6.599999905,5.199999809,4.599999905,0,4.900000095,4.300000191,4,8.399999619,8,8.5,9.399999619,7.800000191,9.300000191,10,9.899999619,8.899999619,8,9.100000381,8.199999809,5,4.599999905,4.699999809,6.5,8,6,3.099999905,5.699999809,6.699999809,6.800000191,1.5,3,7.5,7,5.5,0,4.699999809,7.199999809,5,3.299999952,1,2.5,9.100000381,4.699999809,6.599999905,6.199999809,3.599999905,7,6,10,9.199999809,10,2,10,6.800000191,2.5,10,7.300000191,2.799999952,4.900000095,9,8.5,6.099999905,8.600000381,6.199999809,8.399999619,8,10,10,1,10,1,9.399999619,8.800000191,9.699999809,6.800000191,4.300000191],[0.796000004,null,0.620000005,0.726999998,0.690999985,1,0.796000004,0.796000004,0.726999998,1,0.796000004,1,1,0.656000018,0.796000004,0.726999998,0.195000023,0.18900004,0.195000023,0.796000004,0.690999985,1,0.620000005,0.264000058,0.726999998,0.796000004,1,0.75999999,0.81400001,0.726999998,0.796000004,0.796000004,0.796000004,0.726999998,0.195000023,0.087999992,0.84800005,0.850000024,1,0.620000005,0.726999998,0.690999985,-0.065999962,0.796000004,0.195000023,0.690999985,0.850000024,0.796000004,0.726999998,1,1,0.726999998,0.796000004,0.796000004,0.796000004,1,1,0.725000024,1,0.796000004,0.157000035,1,0.516000032,0.690999985,0.726999998,0.726999998,0.620000005,0.84800005,0.087999992,0.029999996,0.516000032,0.195000023,0.159000009,0.796000004,0.726999998,0.364000022,0.029999996,0.656000018,0.726999998,0.656000018,0.264000058,0.726999998,0.725000024,-0.040999986,0.690999985,0.796000004,0.620000005,0.796000004,0.84800005,0.725000024,1,0.796000004,1,0.726999998,0.796000004,0.656000018,0.796000004,0.087999992,1,0.690999985,0.656000018,0.087999992,0.796000004,1,0.81400001,0.725000024,-0.016000008,0.587000012,1,1,0.726999998,0.195000023,0.796000004,1,0.796000004,0.726999998,0.690999985,0.796000004,0.796000004,null,1,null,0.620000005,0.690999985,0.487000048,0.690999985,0.796000004,0.725000024,0.690999985,1,0.620000005,0.796000004,1,0.159000009,0.690999985,0.516000032,0.159000009,0.656000018,0.656000018,0.75999999,0.087999992,1,0.850000024,0.620000005,0.690999985,0.796000004,0.796000004,0.796000004,0.796000004,0.796000004,1,0.796000004,0.796000004,0.850000024,0.725000024,0.796000004,1,0.710000038,0.725000024,0.620000005,0.796000004,1,0.656000018,0.620000005,1,0.796000004,0.690999985,0.159000009,0.656000018,0.796000004,0.743000031,0.159000009,0.124000005,0.726999998,-0.077,0.159000009,0.087999992,1,0.087999992,0.796000004,0.796000004,1,0.087999992,0.796000004,1,0.195000023,0.75999999,0.690999985,0.690999985,0.796000004,0.087999992,0.75999999,-0.073999979,0.195000023,0.690999985,0.726999998,1,0.264000058,0.193000048,-0.077,0.690999985,0.850000024],[90,null,51,80,85,45,75,50,98,95,95,85,95,90,88,92,90,55,65,100,65,50,74,95,87,90,100,82,77,60,100,95,95,95,100,79,75,55,99,80,50,100,75,65,85,84,89,75,91,62,98,55,60,90,40,55,100,43,95,86,15,70,61,60,75,50,60,65,75,73,50,45,60,15,65,50,39,40,56,40,null,95,95,0,85,100,90,70,98,88,49,85,98,80,100,85,80,54,99,90,55,60,80,80,80,60,40,75,75,80,71,65,50,85,88,70,76,95,89,95,79,94,80,82,40,80,90,70,96,90,70,95,70,95,89,68,85,50,85,100,50,90,50,61,80,80,90,60,70,80,100,50,90,90,50,85,80,81,92,60,88,75,53,66,79,71,80,90,70,70,85,80,60,83,0,null,85,85,35,80,79,80,51,100,80,65,60,70,95,75,50,70,50,50,60,70,100,100,50,30,44,90],[6,null,6,4,4,2,3,4,1,4,4,3,4,3,2,4,6,4,4,4,4,4,4,6,2,4,4,6,4,4,2,4,6,3,4,6,1,6,4,5,2,4,4,1,4,4,4,3,4,3,4,4,4,3,4,4,2,2,3,2,4,4,4,4,4,1,4,3,4,4,6,4,2,4,4,2,4,6,4,4,6,4,2,4,4,2,4,4,2,4,4,6,5,6,2,2,2,4,3,1,4,2,4,4,1,3,1,4,4,6,6,4,1,4,4,3,3,4,4,4,4,4,4,4,2,4,4,1,4,2,4,4,6,4,4,5,4,4,1,4,4,4,2,4,4,4,4,1,2,4,6,4,2,4,4,4,4,1,4,4,5,4,4,4,4,6,4,4,1,2,4,4,6,4,4,4,4,4,4,4,2,4,4,2,3,2,4,3,4,4,4,5,5,3,4,2,6,4,4,4,4,4],[null,null,5,4,2,3,5,10,5,4,2,2,3,2,5,5,6,4,3,4,3,10,4,1,3,7,6,2,3,2,2,4,2,4,3,3,2,2,4,5,3,3,5,5,4,2,3,4,4,4,3,3,4,2,2,3,2,2,2,2,5,3,4,4,8,3,5,2,3,5,3,5,4,2,5,6,2,5,5,5,2,4,3,4,5,5,4,4,2,3,3,1,2,3,3,8,1,4,2,3,2,5,7,4,6,2,3,2,2,2,4,5,2,3,6,5,6,5,6,3,3,3,5,3,6,2,3,3,3,2,3,2,4,4,4,4,3,3,3,4,2,4,3,5,3,5,5,3,5,1,3,5,8,5,3,5,1,3,4,9,4,4,4,8,10,1,5,4,4,10,4,3,3,5,4,4,5,3,4,2,3,3,3,7,3,5,2,4,5,3,5,5,4,6,2,2,2,4,6,3,5,8],[2,null,5,0,1,2,0,10,0,4,2,0,4,1,4,5,0,4,3,4,1,10,2,1,3,6,0,2,3,2,2,2,0,4,3,2,0,2,0,3,null,1,null,0,4,2,null,2,0,0,0,0,2,null,0,3,0,null,2,1,4,null,3,4,8,1,1,0,0,2,3,3,0,0,4,6,0,4,null,3,2,3,0,4,5,0,2,4,1,2,2,0,1,2,3,4,0,0,0,null,0,2,0,1,3,0,3,1,null,null,4,5,0,null,5,3,2,2,6,0,0,0,4,0,null,2,3,3,2,null,0,0,2,null,2,1,1,2,2,2,2,4,2,3,1,6,null,0,0,2,1,0,4,4,1,5,1,3,2,null,3,2,3,5,0,null,0,3,3,3,4,3,0,3,3,3,0,3,3,0,0,1,2,null,0,null,1,4,5,0,2,0,5,5,1,1,0,4,5,3,4,10],[null,null,0,-4,-1,-1,-5,0,-5,0,0,-2,1,-1,-1,0,-6,0,0,0,-2,0,-2,0,0,-1,-6,0,0,0,0,-2,-2,0,0,-1,-2,0,-4,-2,null,-2,null,-5,0,0,null,-2,-4,-4,-3,-3,-2,null,-2,0,-2,null,0,-1,-1,null,-1,0,0,-2,-4,-2,-3,-3,0,-2,-4,-2,-1,0,-2,-1,null,-2,0,-1,-3,0,0,-5,-2,0,-1,-1,-1,-1,-1,-1,0,-4,-1,-4,-2,null,-2,-3,-7,-3,-3,-2,0,-1,null,null,0,0,-2,null,-1,-2,-4,-3,0,-3,-3,-3,-1,-3,null,0,0,0,-1,null,-3,-2,-2,null,-2,-3,-2,-1,-1,-2,0,0,-1,-2,-2,1,null,-3,-5,1,-2,-5,-4,-1,-2,0,0,0,-2,null,-1,-2,-1,-3,-10,null,-5,-1,-1,-7,0,0,-3,-2,-1,-1,-5,0,-1,-2,-3,-2,-1,null,-3,null,-1,0,0,-3,-3,-5,1,-1,-1,-1,-2,0,-1,0,-1,2],[0,null,0,1,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,1,0,null,0,null,1,0,0,null,0,1,1,1,1,0,null,1,0,1,null,0,0,0,null,0,0,0,0,0,1,1,0,0,0,1,1,0,0,1,0,null,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,1,null,1,0,1,0,0,1,0,0,null,null,0,0,1,null,0,0,0,0,0,1,1,1,0,1,null,0,0,0,0,null,1,1,0,null,0,0,0,0,0,0,0,0,0,0,0,0,null,1,1,0,0,1,0,0,0,0,0,0,0,null,0,0,0,0,1,null,1,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,null,1,null,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0],[2,null,5,0,1,2,0,10,0,4,2,0,4,1,4,5,0,4,3,4,1,10,2,1,3,6,0,2,3,2,2,2,0,4,3,2,0,2,0,3,null,1,null,0,4,2,2,2,0,0,0,0,2,null,0,3,0,null,2,1,4,null,3,4,8,1,1,0,0,2,3,3,0,0,4,6,0,4,null,3,2,3,0,4,5,0,2,4,1,2,2,0,1,2,3,4,0,0,0,null,0,2,0,1,3,0,3,1,1,3,4,5,0,0,5,3,2,2,6,0,0,0,4,0,0,2,3,3,2,null,0,0,2,null,2,1,1,2,2,2,2,4,2,3,1,6,null,0,0,2,1,0,4,4,1,5,1,3,2,7,3,2,3,5,0,null,0,3,3,3,4,3,0,3,3,3,0,3,3,0,0,1,2,3,0,null,1,4,5,0,2,0,5,5,1,1,0,4,5,3,4,10],[null,null,0,-4,-1,-1,-5,0,-5,0,0,-2,1,-1,-1,0,-6,0,0,0,-2,0,-2,0,0,-1,-6,0,0,0,0,-2,-2,0,0,-1,-2,0,-4,-2,null,-2,null,-5,0,0,-1,-2,-4,-4,-3,-3,-2,null,-2,0,-2,null,0,-1,-1,null,-1,0,0,-2,-4,-2,-3,-3,0,-2,-4,-2,-1,0,-2,-1,null,-2,0,-1,-3,0,0,-5,-2,0,-1,-1,-1,-1,-1,-1,0,-4,-1,-4,-2,null,-2,-3,-7,-3,-3,-2,0,-1,-1,1,0,0,-2,-3,-1,-2,-4,-3,0,-3,-3,-3,-1,-3,-6,0,0,0,-1,null,-3,-2,-2,null,-2,-3,-2,-1,-1,-2,0,0,-1,-2,-2,1,null,-3,-5,1,-2,-5,-4,-1,-2,0,0,0,-2,-2,-1,-2,-1,-3,-10,null,-5,-1,-1,-7,0,0,-3,-2,-1,-1,-5,0,-1,-2,-3,-2,-1,-4,-3,null,-1,0,0,-3,-3,-5,1,-1,-1,-1,-2,0,-1,0,-1,2],[0,null,0,1,1,1,1,0,1,0,0,1,0,1,1,0,1,0,0,0,1,0,1,0,0,1,1,0,0,0,0,1,1,0,0,1,1,0,1,1,null,1,null,1,0,0,1,1,1,1,1,1,1,null,1,0,1,null,0,1,1,null,1,0,0,1,1,1,1,1,0,1,1,1,1,0,1,1,null,1,0,1,1,0,0,1,1,0,1,1,1,1,1,1,0,1,1,1,1,null,1,1,1,1,1,1,0,1,1,0,0,0,1,1,1,1,1,1,0,1,1,1,1,1,1,0,0,0,1,null,1,1,1,null,1,1,1,1,1,1,0,0,1,1,1,0,null,1,1,0,1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,null,1,1,1,1,0,0,1,1,1,1,1,0,1,1,1,1,1,1,1,null,1,0,0,1,1,1,0,1,1,1,1,0,1,0,1,0],[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[0,null,0,1,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,1,0,null,0,null,1,0,0,0,0,1,1,1,1,0,null,1,0,1,null,0,0,0,null,0,0,0,0,0,1,1,0,0,0,1,1,0,0,1,0,null,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,1,null,1,0,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,1,0,1,1,0,0,0,0,null,1,1,0,null,0,0,0,0,0,0,0,0,0,0,0,0,null,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,null,1,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,1,null,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>id<\/th>\n      <th>group<\/th>\n      <th>center<\/th>\n      <th>gender<\/th>\n      <th>smoking_history<\/th>\n      <th>no_of_corns<\/th>\n      <th>age<\/th>\n      <th>pain_baseline<\/th>\n      <th>eq5d_baseline<\/th>\n      <th>eq5d_VAS_baseline<\/th>\n      <th>index_corn_site<\/th>\n      <th>cornsize_base<\/th>\n      <th>cornsize_3<\/th>\n      <th>cornsize_change<\/th>\n      <th>cornresolved<\/th>\n      <th>cornsize_imp3<\/th>\n      <th>cornsize_change_imp<\/th>\n      <th>healed<\/th>\n      <th>healedknown<\/th>\n      <th>complete_healed<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"deferRender":false,"dom":"t","columnDefs":[{"className":"dt-center","targets":5},{"className":"dt-right","targets":[1,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]},{"orderable":false,"targets":0}],"scrollY":202,"scroller":true,"scrollX":true,"pageLength":5,"order":[],"autoWidth":false,"orderClasses":false,"lengthMenu":[5,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>&nbsp;</p>
<p><a href="#tbl-corn">Table&nbsp;<span>1.1</span></a> presents a typical table with some of the basic characteristics (variables) of patients entered into <span class="citation" data-cites="farndon2013">Farndon et al. (<a href="references.html#ref-farndon2013" role="doc-biblioref">2013</a>)</span> study.</p>
<div id="tbl-corn" class="anchored">
<table class="table">
<caption>Table 1.1: Baseline characteristics of patients with foot corns by treatment group. <span class="citation" data-cites="farndon2013">(<a href="references.html#ref-farndon2013" role="doc-biblioref">Farndon et al. 2013</a>)</span>
</caption>
<colgroup>
<col style="width: 27%">
<col style="width: 21%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead><tr class="header">
<th></th>
<th></th>
<th>
<p>Corn Plaster, n (%)</p>
(n=101)</th>
<th>
<p>Scalpel, n (%)</p>
(n=101)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Gender</strong></td>
<td>Male</td>
<td>42 (42)</td>
<td>42 (42)</td>
</tr>
<tr class="even">
<td></td>
<td>Female</td>
<td>59 (59)</td>
<td>59 (58)</td>
</tr>
<tr class="odd">
<td><strong>Center</strong></td>
<td>Central</td>
<td>58 (57)</td>
<td>52 (52)</td>
</tr>
<tr class="even">
<td></td>
<td>Manor</td>
<td>13 (13)</td>
<td>20 (20)</td>
</tr>
<tr class="odd">
<td></td>
<td>Jordanthorpe</td>
<td>10 (10)</td>
<td>14 (14)</td>
</tr>
<tr class="even">
<td></td>
<td>Limbrick</td>
<td>3 (3)</td>
<td>6 (6)</td>
</tr>
<tr class="odd">
<td></td>
<td>Firth Park</td>
<td>7 (7)</td>
<td>4 (4)</td>
</tr>
<tr class="even">
<td></td>
<td>Huddersfield</td>
<td>5 (5)</td>
<td>4 (4)</td>
</tr>
<tr class="odd">
<td></td>
<td>Darnall</td>
<td>5 (5)</td>
<td>1 (1)</td>
</tr>
<tr class="even">
<td>
<p><strong>Smoking</strong></p>
<p><strong>History</strong></p>
</td>
<td>Non-smoker</td>
<td>34 (35)</td>
<td>40 (40)</td>
</tr>
<tr class="odd">
<td></td>
<td>Previous smoker</td>
<td>22 (22)</td>
<td>16 (16)</td>
</tr>
<tr class="even">
<td></td>
<td>Current smoker</td>
<td>42 (43)</td>
<td>43 (43)</td>
</tr>
<tr class="odd">
<td></td>
<td>Missing</td>
<td>3 (3)</td>
<td>2 (2)</td>
</tr>
<tr class="even">
<td><strong>Numbers of corns</strong></td>
<td>1</td>
<td>48 (48)</td>
<td>66 (65)</td>
</tr>
<tr class="odd">
<td></td>
<td>2</td>
<td>28 (28)</td>
<td>23 (23)</td>
</tr>
<tr class="even">
<td></td>
<td>3</td>
<td>24 (24)</td>
<td>12 (12)</td>
</tr>
<tr class="odd">
<td></td>
<td>Missing</td>
<td>1 (1)</td>
<td>0 (0)</td>
</tr>
<tr class="even">
<td>
<p><strong>Age (yrs),</strong></p>
<p><strong>mean (sd)</strong></p>
</td>
<td></td>
<td>58.5 (15.6)</td>
<td>59.7 (17.5)</td>
</tr>
<tr class="odd">
<td>
<p><strong>Corn size (mm),</strong></p>
<p><strong>median (IQR)</strong></p>
</td>
<td></td>
<td>4 (3, 5)</td>
<td>3 (3, 5)</td>
</tr>
<tr class="even">
<td>
<p><strong>EQ-5D,</strong></p>
<p><strong>median (IQR)</strong></p>
</td>
<td></td>
<td>0.73 (0.59, 0.80)</td>
<td>0.73 (0.66, 0.80)</td>
</tr>
</tbody>
</table>
</div>
<p>In this example since we have 101 patients in each randomized group the percentages are almost the same as the raw counts. However, for most studies we are unlikely to have exactly 100 participants in each group!</p>
</div>
</div>
<p>&nbsp;</p>
<section id="categorical-data" class="level3"><h3 class="anchored" data-anchor-id="categorical-data">Categorical Data</h3>
<p><strong>A. Nominal Data</strong></p>
<p><strong>Nominal categorical data</strong> are data that one can name and put into categories. They are not measured but simply <strong>counted</strong>. They often consist of <strong>unordered</strong> ‘either–or’ type observations which have two categories and are often know as <strong>binary</strong>. For example: dead or alive; male or female; cured or not cured; pregnant or not pregnant. In <a href="#tbl-corn">Table&nbsp;<span>1.1</span></a> gender is a binary variable. However, nominal categorical data often can have <strong>more than two categories</strong>, for example, blood group A, B, AB, 0; country of origin; ethnic group; eye color. The <a href="#tbl-corn">Table&nbsp;<span>1.1</span></a> gives the number and percentages of people treated at each of the seven centers in each of the two randomized groups.</p>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Numerical representation of categories are just codes</strong></p>
<p>We can denote a male and female as 1 and 2 for gender and denote A, B, AB and 0, as 1, 2, 3, and 4 for blood type. Unlike numerical data, the numbers representing different categories do not have mathematical meanings (they are just codes).</p>
</div>
</div>
<p>&nbsp;</p>
<p><strong>Β. Ordinal Data</strong></p>
<p>If there are more than two categories of classification it may be possible to <strong>order</strong> them in some way. For example, after treatment a patient may be either improved, the same or worse. Another example of an ordinal variable is the variable <strong>pain</strong> where a subject is asked to describe their pain verbally as minimal, moderate, severe, or unbearable. In <a href="#tbl-corn">Table&nbsp;<span>1.1</span></a> <strong>smoking history</strong> is given in three categories: non-smoker, previous smoker, and current smoker. Thus, someone who is a current smoker has more recent exposure to tobacco than someone who is an ex-smoker and someone who has never smoked. However, <strong>without further knowledge</strong> (of the current and past levels of tobacco consumption) it would be wrong to ascribe a numerical quantity to the category, for example, non-smoker=0, previous smoker=1, and current smoker=2, as one cannot say that someone who is current smoker has twice the levels of tobacco consumption as someone who is a previous smoker.</p>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Collapsion of categories leads to a loss of information</strong></p>
<p>Ordinal data are often reduced to two categories to simplify analysis and presentation, which may result in a considerable loss of information.</p>
</div>
</div>
<p>&nbsp;</p>
</section><section id="numerical-data" class="level3"><h3 class="anchored" data-anchor-id="numerical-data">Numerical Data</h3>
<p><strong>A. Count (or discrete) Data</strong></p>
<p><a href="#tbl-corn">Table&nbsp;<span>1.1</span></a> gives details of the number of corns each participant had at the start of the trial, since this can only be a whole number or integer value, for example, 0, 1, 2, or 3 in this trial, this is termed count data. Other examples are often counts per unit of time such as the number of deaths in a hospital per year, the number of visits to the GP in a year, or the number of attacks of asthma a person has per month. In dentistry, a common measure is the number of decayed, filled or missing teeth (DFM).</p>
<p>The difference between such data as these and the ordered categorical data described earlier can be seen by considering an example of each:</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<strong>Illustrative Example: Ordinal Vs Discrete data</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><em>Ordinal categorical:</em></strong> Stage of breast cancer: I II III IV</p>
<p><strong><em>Discrete numerical:</em></strong> Number of children: 0 1 2 3 4 5+</p>
<p>We cannot say that stage IV is twice as bad as stage II nor that the difference between stages I and II is equivalent to that between stages III and IV. In contrast, three children are three times as many as one, and a difference of one means the same throughout the range of values.</p>
</div>
</div>
<p>&nbsp;</p>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Discrete Vs Ordinal Data</strong></p>
<p>In practice discrete data are often treated in statistical analyses as if they were ordered categories. This is not wrong, but it may not be getting the most out of the data. Conversely, when ordered categories are numbered, as with stage of disease, the temptation to treat these numbers as statistically meaningful must be resisted. For example, it is not sensible to calculate the average stage of cancer. The only information the numbers contain is in the ordering, which would be conveyed equally by calling them A, B, C, D and so on.</p>
</div>
</div>
<p>&nbsp;</p>
<p><strong>Β. Continuous (or measured) Data</strong></p>
<p>Such data are measurements that can, in theory at least, <strong>take any value within a given range</strong> (they are restricted by the accuracy of the measuring instrument). These data contain the most information, and are the ones most commonly used in statistics. Examples of continuous data in <a href="#tbl-corn">Table&nbsp;<span>1.1</span></a> are: age, corn size, and EQ-5D.</p>
<p>Sometimes it is reasonable to treat discrete data as if they were continuous, at least as far as statistical analysis goes. While age is a continuous measurement, <strong>age at last birthday is discrete</strong>. In studies of adults with ages ranging from, say, 16 to 80, no harm is done in considering age in years as a continuous measurement (and this is standard practice), but for studies of pre-school children it would be better to use age in months. <strong>Heart rate</strong> (in beats per minute) is another discrete measurement that is usually regarded as continuous. Although the essential requirement for this change of status is that there should be a large number of different possible values, in practice we do not worry too much about analysing discrete measurements as if they were continuous.</p>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Categorization of numerical data leads to a loss of information</strong></p>
<p>For simplicity, it is often the case in medicine that continuous data are dichotomized to make nominal data. For example, the diastolic blood pressure (DBP), which is continuous, is converted into hypertension (&gt;90 mmHg) and normotension (≤90 mmHg). There are two main reasons for doing this. It is easier to describe a population by the proportion of people affected, for example, the proportion of people in the population with hypertension is 10%. Further, one often has to make a decision: if a person has hypertension, then they will get treatment, and this is easier if high blood pressure has been categorized. However, this dichotomization clearly leads to a loss of information.</p>
<p>&nbsp;</p>
<p>One can also divide a continuous variable into more than two groups. For example, we could divide age into age bands of equal lengths of, say 10 years such as: 0-9, 10-19, 20-29, etc. When categorizing continuous data authors should give an indication as to why they chose these cut-off points, and a reader has to be very wary to guard against the fact that the cuts may be chosen to make a particular point.</p>
<p>Some statisticians have termed the habit of categorizing continuous variables as <strong>“dichotomania”</strong>, which they regard as poor practice since it loses information and assumes a discontinuous relationship that is unlikely in nature.</p>
</div>
</div>
<p>&nbsp;</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Record the actual values</strong></p>
<p>It is best to record the actual value of blood pressure, haemoglobin, etc. It is easy to convert to categories in the analysis, but the raw data cannot be retrieved later if only categories are recorded. Information is lost with no compensatory gain. Indeed, the statistical analysis of continuous data is more powerful, and often simpler.</p>
<p>&nbsp;</p>
<p>When some calculation is necessary to derive the observation of interest this should be done by the computer. Thus it is much better to record date of birth and date of examination for subsequent calculation of age rather than to rely on mental arithmetic.</p>
</div>
</div>
<p>&nbsp;</p>
<p>The degree of measurement accuracy and the type of data are both important in relation to carrying out a proper statistical analysis.</p>
</section></section><section id="summarizing-categorical-data" class="level2" data-number="1.4"><h2 data-number="1.4" class="anchored" data-anchor-id="summarizing-categorical-data">
<span class="header-section-number">1.4</span> Summarizing Categorical Data</h2>
<p>Binary data are the simplest type of data. Each individual has a label which takes one of two values such as male or female, corn healed or not healed. A simple summary would be to count the different types of labels and find the <strong>frequencies</strong>. The set of frequencies of all the possible categories is called the <strong>frequency distribution</strong> of the variable.</p>
<p>However, a raw count is rarely useful. For example, in <a href="#tbl-corn">Table&nbsp;<span>1.1</span></a> there are more non-smokers in the scalpel group (40 out of 99 or 40%) compared to corn plaster group (34 out of 98 or 35%). It is only when this count is expressed as a proportion (relative frequency) that it becomes useful. Hence the first step to analyzing categorical data is to count the number of observations in each category (frequencies) and express them as <strong>proportions</strong> of the total sample size (relative frequencies).</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<strong>Illustrative Example - Salicylic acid plasters for treatment of foot corns</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Farndon et al.&nbsp;(2013) reports a RCT that investigated the effectiveness of salicylic acid plasters compared with usual scalpel debridement for treatment of foot corns. As we have already mentioned one categorical variable recorded was the center where each trial participant was treated. Trial participants were treated at one of seven centers and the corresponding categories as displayed in <a href="#tbl-centers1">Table&nbsp;<span>1.2</span></a>. The first column shows category (treatment center) names, whilst the second shows the number of individuals in each category together with its percentage contribution to the total. <a href="#tbl-centers1">Table&nbsp;<span>1.2</span></a> clearly shows that the majority (54.5%) of patients were treated at the “Central” treatment center.</p>
<div id="tbl-centers1" class="anchored">
<table class="table">
<caption>Table 1.2: Frequency and percentage distributions of treatment center among 202 patients with corns <span class="citation" data-cites="farndon2013">(<a href="references.html#ref-farndon2013" role="doc-biblioref">Farndon et al. 2013</a>)</span>
</caption>
<thead><tr class="header">
<th>Treatment center</th>
<th>Frequency</th>
<th>Percentage</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Central</td>
<td>110</td>
<td>54.5%</td>
</tr>
<tr class="even">
<td>Manor</td>
<td>33</td>
<td>16.3%</td>
</tr>
<tr class="odd">
<td>Jordanthorpe</td>
<td>24</td>
<td>11.9%</td>
</tr>
<tr class="even">
<td>Limbrick</td>
<td>9</td>
<td>4.5%</td>
</tr>
<tr class="odd">
<td>Firth Park</td>
<td>11</td>
<td>5.4%</td>
</tr>
<tr class="even">
<td>Huddersfield</td>
<td>9</td>
<td>4.5%</td>
</tr>
<tr class="odd">
<td>Darnall</td>
<td>6</td>
<td>3.0%</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>202</td>
<td>100.0%</td>
</tr>
</tbody>
</table>
</div>
<p>In addition to tabulating each variable separately, we might be interested in whether the distribution of patients across each center is the same for each randomized group. <a href="#tbl-centers2">Table&nbsp;<span>1.3</span></a> shows the distribution of the number of patients treated at center by randomized group; in this case it can be said that the treatment center has been <strong><em>cross-tabulated</em></strong> with randomized group. <a href="#tbl-centers2">Table&nbsp;<span>1.3</span></a> is an example of a <strong><em>contingency</em></strong> table with seven rows (representing treatment center) and two columns (randomized group). Note that we are interested in the distribution of patients across the seven centers in each randomized group (to see whether or not we have similar numbers of patients randomized to each treatment within each center), and so the percentages add to 100 down each column, rather than across the rows.</p>
<div id="tbl-centers2" class="anchored">
<table class="table">
<caption>Table 1.3: Cross-tabulation distribution of treatment center by randomized group for 202 patients with corns <span class="citation" data-cites="farndon2013">(<a href="references.html#ref-farndon2013" role="doc-biblioref">Farndon et al. 2013</a>)</span>
</caption>
<thead><tr class="header">
<th></th>
<th>Corn plaster, n(%)</th>
<th>Scalpel, n(%)</th>
<th>All, n(%)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Central</td>
<td>58 (57)</td>
<td>52 (52)</td>
<td>110 (54.5)</td>
</tr>
<tr class="odd">
<td>Manor</td>
<td>13 (13)</td>
<td>20 (20)</td>
<td>33 (16.3)</td>
</tr>
<tr class="even">
<td>Jordanthorpe</td>
<td>10 (10)</td>
<td>14 (14)</td>
<td>24 (11.9)</td>
</tr>
<tr class="odd">
<td>Limbrick</td>
<td>3 (3)</td>
<td>6 (6)</td>
<td>9 (4.5)</td>
</tr>
<tr class="even">
<td>Firth Park</td>
<td>7 (7)</td>
<td>4 (4)</td>
<td>11 (5.4)</td>
</tr>
<tr class="odd">
<td>Huddersfield</td>
<td>5 (5)</td>
<td>4 (4)</td>
<td>9 (4.5)</td>
</tr>
<tr class="even">
<td>Darnall</td>
<td>5 (5)</td>
<td>1 (1)</td>
<td>6 (3.0)</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>101 (100)</td>
<td>101 (100)</td>
<td>202 (100)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>&nbsp;</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Recommendations for reporting numbers</strong></p>
<div id="tbl-rules1" class="anchored">
<table class="table">
<caption>Table 1.4: Reporting numbers and percentages</caption>
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead><tr class="header">
<th>Recommendation</th>
<th>Correct expression</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Numbers</strong></td>
<td></td>
</tr>
<tr class="even">
<td>In a sentence, numbers less than 10 are words.</td>
<td>Smoking history was missing from <strong>three</strong> patients in the corn plaster study group.</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td>In a sentence, numbers 10 or more are numbers.</td>
<td>There are <strong>34</strong> non-smokers patients in the corn plaster group.</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Use words to express any number that begins a sentence, title or heading.</td>
<td>
<strong>Thirty-four</strong> non-smokers patients recorded in the cord plaster group.</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Percentages</strong></td>
<td></td>
</tr>
<tr class="odd">
<td>Report percentages to only one decimal place if the sample size is larger than 100.</td>
<td>In the sample of <strong>202</strong> patients, <strong>4.5%</strong> were treated at the “Limbrick” treatment center.</td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Report percentages with no decimal places if the sample size is less than 100.</td>
<td>In the sample of <strong>98</strong> patients in the corn plaster group, <strong>35%</strong> were non-smokers.</td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Do not use percentages if the sample size is less than 20.</td>
<td>From <strong>16</strong> previous smokers in the scalpel group, <strong>7</strong> were females.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section><section id="displaying-categorical-data" class="level2" data-number="1.5"><h2 data-number="1.5" class="anchored" data-anchor-id="displaying-categorical-data">
<span class="header-section-number">1.5</span> Displaying Categorical Data</h2>
<p>While frequency tables are extremely useful, the best way to investigate a data set is to plot it. For categorical variables, such as gender and treatment center, it is straightforward to present the number in each category, usually indicating the frequency and percentage of the total number of patients. When shown graphically this is called a <strong>bar plot</strong>.</p>
<p>&nbsp;</p>
<p><strong>A. Simple Bar Plot</strong></p>
<p>A simple bar plot is an easy way to make comparisons across categories. <a href="#fig-barplot1">Figure&nbsp;<span>1.3</span></a> shows the centers where 202 patients with foot corns were treated in the trial of <span class="citation" data-cites="farndon2013">Farndon et al. (<a href="references.html#ref-farndon2013" role="doc-biblioref">2013</a>)</span>. Along the horizontal axis (x-axis) are the different treatment centers whilst on the vertical axis (y-axis) is the percentage. The height of each bar represents the percentage of the total patients in that category. For example, it can be seen that the percentage of participants who were treated in the “Central” center was about 55%.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-barplot1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="introduction_files/figure-html/fig-barplot1-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 1.3: Bar plot showing where 202 patients with corns were treated <span class="citation" data-cites="farndon2013">(<a href="references.html#ref-farndon2013" role="doc-biblioref">Farndon et al. 2013</a>)</span>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<strong>Basic Properties of Simple Bar plot</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>All rectangular bars should have equal width and should have equal space between them.</p></li>
<li><p>The rectangular bars can be drawn horizontally or vertically.</p></li>
<li><p>The height of the rectangular bar is equivalent to the data they represent.</p></li>
<li><p>The rectangular bars must be plotted against a common zero-valued baseline.</p></li>
</ul>
</div>
</div>
<p>&nbsp;</p>
<p><strong>B. Side-by-side and Grouped Bar Plots</strong></p>
<p>If the sample is further classified into whether the patient was treated with corn plasters or scalpel then it becomes impossible to present the data as a single bar plot. We could present the data as a side by side bar plot (see <a href="#fig-barplot2">Figure&nbsp;<span>1.4</span></a>) but is preferable to present the data in one graph with the same scales and axes to make the visual comparisons easier (grouped bar plot) (see <a href="#fig-barplot3">Figure&nbsp;<span>1.5</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-barplot2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="introduction_files/figure-html/fig-barplot2-1.png" class="img-fluid figure-img" width="912"></p>
<p></p><figcaption class="figure-caption">Figure 1.4: Side-by-side bar plot showing where 202 patients with corns were treated by randomized group <span class="citation" data-cites="farndon2013">(<a href="references.html#ref-farndon2013" role="doc-biblioref">Farndon et al. 2013</a>)</span>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-barplot3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="introduction_files/figure-html/fig-barplot3-1.png" class="img-fluid figure-img" width="864"></p>
<p></p><figcaption class="figure-caption">Figure 1.5: Grouped bar plot showing where 202 patients with corns were treated by randomized group <span class="citation" data-cites="farndon2013">(<a href="references.html#ref-farndon2013" role="doc-biblioref">Farndon et al. 2013</a>)</span>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Report the actual total sample sizes for each group</strong></p>
<p>If we do use the relative frequency scale as we have, then it is recommended to report the actual total sample sizes for each group (e.g., in the legend or caption). In this way, given the total sample size and relative frequency (from the height of the bars) we can work out the actual numbers treated in each center.</p>
</div>
</div>
<p>&nbsp;</p>
<p><strong>C. Stacked Bar Plot</strong></p>
<p>Unlike a side-by-side or grouped graphs, <strong>Stacked Bar Plots</strong> segment their bars. A <strong>100% Stack Bar Plot</strong> shows the percentage-of-the-whole of each group and are plotted by the percentage of each value to the total amount in each group. This makes it easier to see if relative differences exist between quantities in each group (see <a href="#fig-stacked">Figure&nbsp;<span>1.6</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-stacked" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="introduction_files/figure-html/fig-stacked-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 1.6: A horizontal 100% stacked bar plot showing the distribution of gender by randomized group <span class="citation" data-cites="farndon2013">(<a href="references.html#ref-farndon2013" role="doc-biblioref">Farndon et al. 2013</a>)</span>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-stacked">Figure&nbsp;<span>1.6</span></a> the bars are divided into two segments only (i.e., female and male) so it is easy to read the values of each segment and to compare a specific segment through the entire set of bars (in our case the percentages are equal). This comparison can be easily made because each segment is aligned through the entire set of bars (female to the left and men to the right). If more segments were added, however, the segments in the middle would not be aligned to the left or right, which would make comparisons difficult (see <a href="#fig-stacked2">Figure&nbsp;<span>1.7</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-stacked2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="introduction_files/figure-html/fig-stacked2-1.png" class="img-fluid figure-img" width="1104"></p>
<p></p><figcaption class="figure-caption">Figure 1.7: A horizontal 100% stacked bar plot showing the distribution of treatment centers by randomized group <span class="citation" data-cites="farndon2013">(<a href="references.html#ref-farndon2013" role="doc-biblioref">Farndon et al. 2013</a>)</span>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Stacked bar plots tend to become confusing when the variable has many levels</strong></p>
<p>One issue to consider when using stacked bar plots is the number of variable levels: when dealing with many categories, stacked bar plots tend to become rather confusing.</p>
</div>
</div>
</section><section id="summarizing-numerical-data" class="level2" data-number="1.6"><h2 data-number="1.6" class="anchored" data-anchor-id="summarizing-numerical-data">
<span class="header-section-number">1.6</span> Summarizing Numerical Data</h2>
<p>A quantitative measurement contains more information than a categorical one, and so summarizing these data is more complex. One chooses summary statistics to condense a large amount of information into a few intelligible numbers, the sort that could be communicated verbally. The two most important pieces of information about a quantitative measurement are <strong>‘where is it?’</strong> and <strong>‘how variable is it?’</strong> These are categorized as <strong>measures of location</strong> (or sometimes ‘central tendency’) and <strong>measures of spread</strong> or variability.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<strong>Two summary measures should be reported for a numerical variable</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p>A measure of <strong>location</strong> (where the center of the distribution of the values is located) and <strong>variability</strong> (how widely the values are spread above and below the central value) provides an informative but brief summary of a set of observations.</p>
</div>
</div>
<p>&nbsp;</p>
<section id="measures-of-location" class="level3"><h3 class="anchored" data-anchor-id="measures-of-location">Measures of Location</h3>
<p><strong>A. Sample Mean or Average</strong></p>
<p>Let <span class="math inline">\(x_1, x_2,...,x_{n-1}, x_n\)</span> be a set of <em>n</em> measurements. The arithmetic sample mean or average, <span class="math inline">\(\bar{x}\)</span> (pronounced x bar), is simply the sum of the observations divided by their number <em>n</em>, thus:</p>
<p><span class="math display">\[
\bar{x}= \frac{Sum \ of \ all \ sample \ values }{Size \ of \ sample}= \frac{x_1 + x_2 + ... + x_{n-1} + x_n}{n}
\]</span></p>
<p>This formula is entirely correct, but it’s too long, so we make use of the <strong><em>summation symbol</em></strong> <span class="math inline">\(\scriptstyle\sum\)</span> to shorten it:</p>
<p><span id="eq-mean"><span class="math display">\[\bar{x}=\frac{\sum_{i=1}^{n}x_{i}}{n}=\frac{1}{n}\sum_{i=1}^{n}x_{i} \tag{1.1}\]</span></span></p>
<p>In the above <a href="#eq-mean">Equation&nbsp;<span>1.1</span></a>, <span class="math inline">\(x_{i}\)</span> represents the individual sample values and <span class="math inline">\({\sum_{i=1}^{n}x_{i}}\)</span> their sum. The Greek letter <span class="math inline">\({\Sigma}\)</span> (sigma) is the Greek capital ‘S’ and stands for ‘sum’ and simply means ‘add up the <em>n</em> observations <span class="math inline">\(x_{i}\)</span> from the 1st to the last (nth)’.</p>
<p>Usually, we cannot measure the population mean <span class="math inline">\({\mu}\)</span>, which is the unknown constant that we want to estimate using the sample mean <span class="math inline">\(\bar{x}\)</span>.</p>
<p>&nbsp;</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<strong>Example: Calculation of the Mean - Corn size data (mm)</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the RCT by <span class="citation" data-cites="farndon2013">Farndon et al. (<a href="references.html#ref-farndon2013" role="doc-biblioref">2013</a>)</span>, the baseline size of the corn (as its widest diameter in mm) was measured by a podiatrist (foot specialist). Consider the following 16 baseline corn sizes selected from the patients:</p>
<p>2, 2, 6, 3, 4, 2, 2, 5, 3, 4, 1, 2, 6, 3, 10, 3</p>
<p>&nbsp;</p>
<p>The sum of the 16 observations is:</p>
<p><span class="math inline">\(2 + 2 + 6 + 3 + 4 + 2 + 2 + 5 + 3 + 4 + 1 + 2 + 6 + 3 + 10 + 3\)</span> = 58</p>
<p>&nbsp;</p>
<p>Thus, the arithmetic mean is:</p>
<p><span class="math inline">\(\bar{x}\)</span> = 58/16 = 3.625 mm or 3.6 mm. It is usual to report one more decimal place for the mean than the data recorded.</p>
</div>
</div>
<p>The major advantage of the mean is that it uses all the data values, while the main disadvantage is its sensitivity to very large or very small values, which might be <strong>outliers</strong> (unusual values). For example, if we entered “100 mm” instead of “10 mm”, for the 15th patient, in the calculation of the mean, we would find the mean changed from 3.6 to 9.2. It does not necessarily follow, however, that outliers should be excluded from the final data summary, or that they result from a human error. Outliers can be legitimate anomalies that are vital for capturing information on the subject of interest.</p>
<p>If the data are binary and are coded 0 or 1, then <span class="math inline">\(\bar{x}\)</span> is the proportion of individuals with value 1, and this can also be expressed as a percentage. In <span class="citation" data-cites="farndon2013">Farndon et al. (<a href="references.html#ref-farndon2013" role="doc-biblioref">2013</a>)</span> data, the cases in which the corn was healed are coded as ‘1s’ and the cases in which the corn was not healed as ‘0s’. The corn had healed in 52 out of 189 patients, so the mean of this variable is 0.275 or 28%.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<strong>Advantages and Disadvantages of arithmetic mean</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Advantages of mean</strong></p>
<ol type="1">
<li>is simple to understand and easy to calculate</li>
<li>uses all the data values in the calculation</li>
<li>is algebraically defined and thus mathematically manageable</li>
<li>has a known sampling distribution</li>
</ol>
<p>&nbsp;</p>
<p><strong>Disadvantages of mean</strong></p>
<ol type="1">
<li>is highly affected by the presence of a few abnormally high or abnormally low values (outliers)</li>
<li>is not an appropriate average for highly skewed (asymmetrical) distributions</li>
<li>cannot be determined if any item of observation is missing</li>
<li>cannot be determined easily by inspection of the data</li>
</ol>
</div>
</div>
<p>&nbsp;</p>
<p><strong>B. Median</strong></p>
<p>The <strong>sample median</strong>, <em>md</em>, is an alternative measure of location, which is less sensitive to outliers. For observed values <span class="math inline">\(x_1, x_2,...,x_{n-1}, x_n\)</span> the median is calculated by first sorting the observed values (i.e., arranging them in an ascending/descending order) and selecting the middle one. If the sample size <em>n</em> is <strong>odd</strong>, the median is the number at the middle of the ordered observations. If the sample size is <strong>even</strong>, the median is the average of the two middle numbers.</p>
<p>Therefore, the sample median, <em>md</em>, of <em>n</em> observations is:</p>
<ul>
<li><p>the <span class="math inline">\(\frac{n+1}{2}\)</span>th ordered value, <span class="math inline">\(md=x_{\frac{n+1}{2}}\)</span>, if <em>n</em> is odd.</p></li>
<li><p>the average of the <span class="math inline">\(\frac{n}{2}\)</span>th and <span class="math inline">\(\frac{n+1}{2}\)</span>th ordered values, <span class="math inline">\(md=\frac{1}{2}(x_{\frac{n}{2}}+x_{\frac{n+1}{2}})\)</span>, if <em>n</em> is even.</p></li>
</ul>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<strong>Example: Calculation of the Median - Corn size data (mm)</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>1st case: Even observations</strong></p>
<blockquote class="blockquote">
<p>We have selected 16 baseline corn sizes:</p>
<p><strong>original data:</strong> 2, 2, 6, 3, 4, 2, 2, 5, 3, 4, 1, 2, 6, 3, 10, 3</p>
<p>We arrange the data in an ascending order:</p>
<p><strong>ordered data:</strong> 1, 2, 2, 2, 2, 2, 3, <strong>3</strong>, <strong>3</strong>, 3, 4, 4, 5, 6, 6, 10</p>
<p>As the number of observations are <strong>even</strong> (n=16), the median is the average of the two middle ordered numbers (the eighth and ninth): (3+3)/2=3 mm.</p>
</blockquote>
<p>&nbsp;</p>
<p><strong>2nd case: Odd observations</strong></p>
<blockquote class="blockquote">
<p>Suppose we select an additional 17th subject with corn size of 10 mm, so the data are as following:</p>
<p><strong>original data:</strong> 2, 2, 6, 3, 4, 2, 2, 5, 3, 4, 1, 2, 6, 3, 10, 3, 10</p>
<p>We arrange the data in an ascending order:</p>
<p><strong>ordered data:</strong> 1, 2, 2, 2, 2, 2, 3, 3, <strong>3</strong>, 3, 4, 4, 5, 6, 6, 10, 10</p>
<p>The median would be the 9th ordered observation, which is also 3 mm.</p>
</blockquote>
<p>&nbsp;</p>
<p><strong>Main Advantages and Disadvantages of median</strong></p>
<p>The median has the advantage that is not affected by outliers, so for example, the median in the data would be unaffected by replacing the largest corn size of 10 mm with 100 mm. However, it does not take into account the precise value of each observation and hence does not use all information available in the data.Additionally, it is not a good measure of central tendency when there are heavy ties in the data.</p>
</div>
</div>
<p>&nbsp;</p>
<p><strong>C. Mode</strong></p>
<p>A third measure of location is termed the <strong>mode</strong>. This is the value that occurs <strong>most frequently</strong>, or, if the data are grouped, the group with the highest frequency. It is not used much in statistical analysis, since its value depends on the accuracy with which the data are measured and ignores most of the information; although it may be useful for categorical data to describe the most frequent category. Note that some data sets do not have a mode because each value occurs only once.</p>
<p>However, the expression <strong>‘bimodal’</strong> distribution is used to describe a distribution with <strong>two peaks</strong> in it. This can be caused by mixing two or more populations together. For example, height might appear to have a bimodal distribution if one had men and women in the population.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example: Calculation of the Mode - Corn size data (mm)
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>original data:</strong> <strong>2</strong>, <strong>2</strong>, 6, 3, 4, <strong>2</strong>, <strong>2</strong>, 5, 3, 4, 1, <strong>2</strong>, 6, 3, 10, 3</p>
<p>In the 16 patients with corns, 5 patients have corn size of 2 mm; thus, the <strong>modal corn size is 2 mm</strong>.</p>
</div>
</div>
<p>&nbsp;</p>
</section><section id="measures-of-dispersion" class="level3"><h3 class="anchored" data-anchor-id="measures-of-dispersion">Measures of Dispersion</h3>
<p>We also need a numerical way of summarizing the amount of spread or variability in a data set. The tree main approaches to quantifying variability are: the range, the interquartile range (IQR), and the standard deviation.</p>
<p><strong>A. Range</strong></p>
<p>The simplest way to describe the spread of a data set is to report the minimum (lowest) and maximum (highest) values. The <strong>range</strong> is defined as the difference between the largest and the smallest observations in a sample. For some data it is very useful, because one would want to know these numbers, for example in a sample the age of the youngest and oldest participant. However, if outliers are present it may give a distorted impression of the variability of the data, since only two of the data points are included in making the estimate. Thus the range is <strong>affected by extreme values</strong> at each end of the data.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example: Calculation of the Range - Corn size data (mm)
</div>
</div>
<div class="callout-body-container callout-body">
<p>The range for the corn size data is 1 to 10 mm or described by a single number 10-1 = 9 mm.</p>
</div>
</div>
<p>&nbsp;</p>
<p><strong>B. Quartiles and Interquartile Range</strong></p>
<p>The <strong>quartiles</strong>, namely the lower quartile (<span class="math inline">\(Q_{1}\)</span>), the median (<span class="math inline">\(Q_{2}\)</span>) and the upper quartile (<span class="math inline">\(Q_{3}\)</span>), split sorted data into four equal parts. That is there will be approximately equal numbers of observations in the four sections (and exactly equal if the sample size is divisible by four and the measures are all distinct). The quartiles are calculated in a similar way to the median; first order the data and then count the appropriate number from the bottom. The <span class="math inline">\(Q_{1}\)</span> is the value below which 25% of the observations may be found, while the <span class="math inline">\(Q_{3}\)</span> is the value above which the top 25% of the observations may be found (meaning that 75% of the data falls below the <span class="math inline">\(Q_{3}\)</span>).</p>
<p>The <strong>interquartile range</strong> (IQR) is a useful measure of variability and is given by the difference of the lower and upper quartiles (IQR=<span class="math inline">\(Q_{3}\)</span>-<span class="math inline">\(Q_{1}\)</span>). It indicates the spread of the middle 50% (75%-25%) of the data.The IQR is an especially good measure of variability for skewed distributions or distributions with outliers.</p>
<p>The median and the quartiles are examples of <strong>percentiles</strong> - points which split the distribution of data into percentages above or below a certain value. The median is the 50th percentile, the <span class="math inline">\(Q_{1}\)</span> is the 25th percentile, and the the <span class="math inline">\(Q_{3}\)</span> is the 75th percentile.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example: Calculation of the Quartiles and Interquartile Range - Corn size data (mm)
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <span class="math inline">\(Q_{1}\)</span> lies somewhere between the <span class="math inline">\(\color{red}{fourth}\)</span> and <span class="math inline">\(\color{blue}{fifth}\)</span> ordered observations (2+2)/2= 2mm. The median, <span class="math inline">\(Q_{2}\)</span>, is the average of the <span class="math inline">\(\color{blue}{eighth}\)</span> and <span class="math inline">\(\color{green}{ninth}\)</span> ordered observations (3+3)/2=3 mm. Similarly, The <span class="math inline">\(Q_{3}\)</span> lies somewhere between the <span class="math inline">\(\color{green}{12th}\)</span> and <span class="math inline">\(\color{orange}{13th}\)</span> ordered observations (4+5)/2= 4.5 mm.</p>
<p>So, the IQR for the corn size data is from 2.0 to 4.5 mm; or a single number 2.5 mm.</p>
<div id="tbl-quartiles" class="anchored">
<table class="table">
<caption>Table 1.5: Calculating quartiles for the corn size data</caption>
<colgroup>
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<tbody><tr class="odd">
<td><strong>Ordered corn size (mm)</strong></td>
<td><span class="math inline">\(\color{red}{1}\)</span></td>
<td><span class="math inline">\(\color{red}{2}\)</span></td>
<td><span class="math inline">\(\color{red}{2}\)</span></td>
<td><span class="math inline">\(\color{red}{\textbf{2}}\)</span></td>
<td><span class="math inline">\(\color{blue}{\textbf{2}}\)</span></td>
<td><span class="math inline">\(\color{blue}{2}\)</span></td>
<td><span class="math inline">\(\color{blue}{3}\)</span></td>
<td><span class="math inline">\(\color{blue}{\textbf{3}}\)</span></td>
<td><span class="math inline">\(\color{green}{\textbf{3}}\)</span></td>
<td><span class="math inline">\(\color{green}{3}\)</span></td>
<td><span class="math inline">\(\color{green}{4}\)</span></td>
<td><span class="math inline">\(\color{green}{\textbf{4}}\)</span></td>
<td><span class="math inline">\(\color{orange}{\textbf{5}}\)</span></td>
<td><span class="math inline">\(\color{orange}{6}\)</span></td>
<td><span class="math inline">\(\color{orange}{6}\)</span></td>
<td><span class="math inline">\(\color{orange}{10}\)</span></td>
</tr></tbody>
</table>
</div>
<p>The range for the corn size data is 1 to 10 mm or described by a single number 10-1 = 9 mm.</p>
</div>
</div>
<p>&nbsp;</p>
<p><strong>C. Variance and Standard Deviation</strong></p>
<p>For an individual with an observed value <span class="math inline">\(x_{i}\)</span> the distance from the mean is <span class="math inline">\(x_{i}-\bar{x}\)</span>. With <em>n</em> such observations we have a set of <em>n</em> differences, one for each individual. The sum of the differences, <span class="math inline">\({\sum_{i=1}^{n}(x_{i}-\bar{x})}\)</span> is always zero. However, if we square the distances before we sum them, we get always a positive quantity.This sum is then divided by <strong>n-1</strong> and thus gives an average measure for the square of the deviation from the sample mean. This quantity is called the sample <strong>variance</strong> and is defined as <a href="#eq-var">Equation&nbsp;<span>1.2</span></a>:</p>
<p><span id="eq-var"><span class="math display">\[variance = s^2 = \frac{\sum\limits_{i=1}^n (x -\bar{x})^2}{n-1} \tag{1.2}\]</span></span></p>
<p>The variance is expressed in square units, so we can take the square root to return to the original units. This gives us the <strong>standard deviation</strong> (usually abbreviated as sd) defined as <a href="#eq-sd">Equation&nbsp;<span>1.3</span></a>:</p>
<p><span id="eq-sd"><span class="math display">\[sd=s = \sqrt\frac{\sum_{i=1}^{n}(x_{i}-\bar{x})^2}{n-1} \tag{1.3}\]</span></span></p>
<p>Examining this expression it can be seen that if all the <em>x’s</em> were the same, then they would equal <em>x</em> and so <em>sd</em> would be zero. If the x’s were widely scattered about <em>x</em>, then <em>sd</em> would be large. In this way <em>sd</em> reflects the variability in the data. Both, variance and standard deviation, are sensitive to outliers and thus they are inappropriate for skewed data.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example: Calculation of the Variance and Standard Deviation - Corn size data (mm)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider the 16 observations from the corn data. The calculations to work out the standard deviation are given in the <a href="#tbl-sd">Table&nbsp;<span>1.6</span></a>.</p>
<div id="tbl-sd" class="anchored">
<table class="table">
<caption>Table 1.6: Calculating variance and standard deviation for the corn size data</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 30%">
<col style="width: 39%">
</colgroup>
<thead><tr class="header">
<th>id</th>
<th>Corn size (mm)</th>
<th>Mean</th>
<th>Difference from mean <span class="math inline">\((x_{i}-\bar{x})\)</span>
</th>
<th>Square of difference from mean <span class="math inline">\((x_{i}-\bar{x})^2\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2</td>
<td>3.625</td>
<td>-1.625</td>
<td>2.641</td>
</tr>
<tr class="even">
<td>2</td>
<td>2</td>
<td>3.625</td>
<td>-1.625</td>
<td>2.641</td>
</tr>
<tr class="odd">
<td>3</td>
<td>6</td>
<td>3.625</td>
<td>2.375</td>
<td>5.641</td>
</tr>
<tr class="even">
<td>4</td>
<td>3</td>
<td>3.625</td>
<td>-0.625</td>
<td>0.391</td>
</tr>
<tr class="odd">
<td>5</td>
<td>4</td>
<td>3.625</td>
<td>0.375</td>
<td>0.141</td>
</tr>
<tr class="even">
<td>6</td>
<td>2</td>
<td>3.625</td>
<td>-1.625</td>
<td>2.641</td>
</tr>
<tr class="odd">
<td>7</td>
<td>2</td>
<td>3.625</td>
<td>-1.625</td>
<td>2.641</td>
</tr>
<tr class="even">
<td>8</td>
<td>5</td>
<td>3.625</td>
<td>1.375</td>
<td>1.891</td>
</tr>
<tr class="odd">
<td>9</td>
<td>3</td>
<td>3.625</td>
<td>-0.625</td>
<td>0.391</td>
</tr>
<tr class="even">
<td>10</td>
<td>4</td>
<td>3.625</td>
<td>0.375</td>
<td>0.141</td>
</tr>
<tr class="odd">
<td>11</td>
<td>1</td>
<td>3.625</td>
<td>-2.625</td>
<td>6.891</td>
</tr>
<tr class="even">
<td>12</td>
<td>2</td>
<td>3.625</td>
<td>-1.625</td>
<td>2.641</td>
</tr>
<tr class="odd">
<td>13</td>
<td>6</td>
<td>3.625</td>
<td>2.375</td>
<td>5.641</td>
</tr>
<tr class="even">
<td>14</td>
<td>3</td>
<td>3.625</td>
<td>-0.625</td>
<td>0.391</td>
</tr>
<tr class="odd">
<td>15</td>
<td>10</td>
<td>3.625</td>
<td>6.375</td>
<td>40.641</td>
</tr>
<tr class="even">
<td>16</td>
<td>3</td>
<td>3.625</td>
<td>-0.625</td>
<td>0.391</td>
</tr>
<tr class="odd">
<td><strong>Sum</strong></td>
<td><strong>58</strong></td>
<td><strong>3.625</strong></td>
<td><strong>0.000</strong></td>
<td><strong>75.756</strong></td>
</tr>
</tbody>
</table>
</div>
<p>From the <a href="#eq-sd">Equation&nbsp;<span>1.3</span></a> we have:</p>
<p><span class="math display">\[sd = \sqrt\frac{\sum_{i=1}^{16}(x_{i}-\bar{x})^2}{16-1} = \sqrt\frac{75.756}{15}= \sqrt{5.05}=2.247 \ or \ 2.3 \ mm\]</span></p>
<p>Note that the majority of this sum is contributed by one observation, the value of 10 mm from participant 15, which is the observation further from the mean. This shows that much of the value of an <em>sd</em> is derived from the outlying observation.</p>
<p>&nbsp;</p>
<p><strong>Why is the standard deviation useful?</strong></p>
<blockquote class="blockquote">
<p>It turns out in many situations that about <strong>95% of observations</strong> will be within <strong>two standard deviations of the mean</strong>. This is known as a reference interval and it is this characteristic of the standard deviation which makes it so useful. It holds for a large number of measurements commonly made in medicine. In particular it holds for data that follow a <strong>Normal distribution</strong> (see Chapter XX). For example, if the age of participants in the corn plaster group is normally distributed, we would expect the majority of participants in this treatment group to have age between 58.5-2 <span class="math inline">\(\times\)</span> 15.6 and 58.5+2 <span class="math inline">\(\times\)</span> 15.6 or 27.3 and 89.7 years.</p>
</blockquote>
</div>
</div>
<p>&nbsp;</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>How to report summary statistics for numerical data?</strong></p>
<p>Mean and median convey different impressions of the location of data. If the distribution is <strong>symmetric</strong>, then in general the <strong>mean</strong> is the better summary statistic, and if it is <strong>skewed</strong> then the <strong>median</strong> is less influenced by the tails. Thus, the following format is recommended:</p>
<blockquote class="blockquote">
<p><strong>Mean (sd)</strong> for data with <strong>symmetric</strong> distribution.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Median (Q1, Q3)</strong> for those with <strong>skewed</strong> distribution.</p>
</blockquote>
<p>&nbsp;</p>
<p><a href="#tbl-rules2">Table&nbsp;<span>1.7</span></a> presents recommendations for reporting summary statistics for numerical data.</p>
<div id="tbl-rules2" class="anchored">
<table class="table">
<caption>Table 1.7: Recommendations for reporting summary statistics</caption>
<colgroup>
<col style="width: 37%">
<col style="width: 62%">
</colgroup>
<thead><tr class="header">
<th><strong>Recommendation</strong></th>
<th><strong>Correct expression</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Do not imply greater precision than the measurement instrument</td>
<td>Only use one decimal place more than the basic unit of measurement when reporting statistics (means, medians, standard deviations, inter-quartile ranges, etc.), for example, the mean age of participants in the corn plaster group was <strong>58.5</strong> years.</td>
</tr>
<tr class="even">
<td>For ranges use ‘to’ or a comma but not ‘-’ to avoid confusion with a minus sign. Also use the same number of decimal places as the summary statistic</td>
<td>
<p>The <strong>mean (sd)</strong> age of participants in the corn plaster group was <strong>58.5 years (15.6)</strong>.</p>
<p>The <strong>median (IQR)</strong> EQ-5D of participants in the corn plaster group was <strong>0.73 (0.59, 0.80)</strong></p>
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section></section><section id="displaying-numerical-data" class="level2" data-number="1.7"><h2 data-number="1.7" class="anchored" data-anchor-id="displaying-numerical-data">
<span class="header-section-number">1.7</span> Displaying Numerical Data</h2>
<p>The best way for examining the distribution of numerical data is to generate an appropriate graph.</p>
<p><strong>A. Histogram and density plot</strong></p>
<p>The most common way of depicting a frequency distribution of a continuous variable is with a histogram.</p>
<p>A histogram (<a href="#fig-histo1">Figure&nbsp;<span>1.8</span></a> a) is a plot that depicts the distribution of a numeric variable’s values as a series of bars without space between them. Each bar typically covers a range of numeric values called a bin or class; a bar’s height indicates the frequency of observations with a value within the corresponding bin. A density plot (<a href="#fig-histo1">Figure&nbsp;<span>1.8</span></a> b) is a smoothed, continuous version of a histogram estimated from the data. In a density plot the total area under the curve integrates to one.</p>
<p><a href="#fig-histo1">Figure&nbsp;<span>1.8</span></a> shows the distribution of age for the participants in <span class="citation" data-cites="farndon2013">Farndon et al. (<a href="references.html#ref-farndon2013" role="doc-biblioref">2013</a>)</span> study. The vertical scale shows (a) frequency (histogram) or (b) probability density (density plot).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-histo1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="introduction_files/figure-html/fig-histo1-1.png" class="img-fluid figure-img" width="720"></p>
<p></p><figcaption class="figure-caption">Figure 1.8: Distribution of age of the participants in <span class="citation" data-cites="farndon2013">Farndon et al. (<a href="references.html#ref-farndon2013" role="doc-biblioref">2013</a>)</span> study (a) histogram (b) density plot.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A histogram (or density plot) gives information about:</p>
<ul>
<li><p>How the data are distributed: (a) left-skewed, (b) symmetric (e.g., normal distribution), (c) right-skewed and if there are any outliers.</p></li>
<li><p>The amount of variability in the data.</p></li>
<li><p>Where the peaks of the distribution are.</p></li>
</ul>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Choose an appropriate number of bins
</div>
</div>
<div class="callout-body-container callout-body">
<p>While tools that can generate histograms usually have some default algorithms for selecting bin boundaries, we will likely want to play around with the binning parameters to choose something that is representative of our data.</p>
<p>Choice of bin size has an inverse relationship with the number of bins <a href="#fig-histo2">Figure&nbsp;<span>1.9</span></a>. The smaller the bin sizes, the more bins there will be to cover the whole range of data. With a larger bin size, the fewer bins there will need to be. It is worth taking some time to test out different bin sizes to see how the distribution looks in each one, then choose the plot that represents the data best.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-histo2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="introduction_files/figure-html/fig-histo2-1.png" class="img-fluid figure-img" width="816"></p>
<p></p><figcaption class="figure-caption">Figure 1.9: Histogram of age for different bin sizes (a) bin size = 5, (b) bin size = 10, and (c) bin size = 15.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>If we have too many bins, then the data distribution will look rough, and it will be difficult to discern the signal from the noise (<a href="#fig-histo2">Figure&nbsp;<span>1.9</span></a> a). On the other hand, with too few bins, the histogram will lack the details needed to discern any useful pattern from the data (<a href="#fig-histo2">Figure&nbsp;<span>1.9</span></a> b).</p>
</div>
</div>
<p>We can also create a histogram or density plot by group. <a href="#fig-histo3">Figure&nbsp;<span>1.10</span></a> depicts the probability density of age by treatment group.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-histo3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="introduction_files/figure-html/fig-histo3-1.png" class="img-fluid figure-img" width="720"></p>
<p></p><figcaption class="figure-caption">Figure 1.10: Histogram of age of participants in <span class="citation" data-cites="farndon2013">Farndon et al. (<a href="references.html#ref-farndon2013" role="doc-biblioref">2013</a>)</span> study by treatment group.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Histograms must be plotted with a zero-valued baseline</strong></p>
<p>An important aspect of histograms is that they must be plotted with a zero-valued baseline. Since the frequency of data in each bin is implied by the height of each bar, changing the baseline or introducing a gap in the scale will skew the perception of the distribution of data.</p>
</div>
</div>
<p>&nbsp;</p>
<p><strong>B. Box Plot</strong></p>
<p>A box plot chart is another graph that can be used for conveying location and variation information for continuous data, particularly for detecting changes between different groups of data before any formal analyses are performed.</p>
<p>A box plot (aka box and whisker plot) uses boxes and lines to depict the distributions of one or more groups of numerical data. Box limits indicate the range of the central <strong>50%</strong> of the data, with a central line marking the <strong>median</strong> value. Lines extend from each box to capture the <strong>range</strong> of the remaining data, with <strong>dots</strong> placed past the line edges to indicate outliers.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-boxplot1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="images/boxplot.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 1.11: Broad classification of the different types of data with examples</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-boxplot1">Figure&nbsp;<span>1.11</span></a> the distance between <span class="math inline">\({Q3}\)</span> and <span class="math inline">\({Q1}\)</span> is the interquartile range (IQR) and plays a major part in how long the whiskers extending from the box are. Each whisker extends to the furthest data point in each wing that is within 1.5 times the IQR. Any data point further than that distance is considered an outlier, and is marked with a dot. There are other ways of defining the whisker lengths, which are not presented in this textbook.</p>
<p><a href="#fig-boxplot2">Figure&nbsp;<span>1.12</span></a> illustrates a box plot that presents the age of participants in <span class="citation" data-cites="farndon2013">Farndon et al. (<a href="references.html#ref-farndon2013" role="doc-biblioref">2013</a>)</span> study.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="introduction_files/figure-html/fig-boxplot2-1.png" class="img-fluid figure-img" width="336"></p>
<p></p><figcaption class="figure-caption">Figure 1.12: A box plot of age of the participants in <span class="citation" data-cites="farndon2013">Farndon et al. (<a href="references.html#ref-farndon2013" role="doc-biblioref">2013</a>)</span> study.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><a href="#fig-boxplot3">Figure&nbsp;<span>1.13</span></a> illustrates a grouped box plot that presents the age by treatment group.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="introduction_files/figure-html/fig-boxplot3-1.png" class="img-fluid figure-img" width="624"></p>
<p></p><figcaption class="figure-caption">Figure 1.13: A box plot of age of the participants in <span class="citation" data-cites="farndon2013">Farndon et al. (<a href="references.html#ref-farndon2013" role="doc-biblioref">2013</a>)</span> study.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
</section><section id="exercises" class="level2" data-number="1.8"><h2 data-number="1.8" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">1.8</span> Exercises</h2>
<ul>
<li>First Exercise</li>
<li>Second Exercise</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-farndon2013" class="csl-entry" role="doc-biblioentry">
Farndon, Lisa J, Wesley Vernon, Stephen J Walters, Simon Dixon, Mike Bradburn, Michael Concannon, and Julia Potter. 2013. <span>“The Effectiveness of Salicylic Acid Plasters Compared with <span>‘Usual’</span> Scalpel Debridement of Corns: A Randomised Controlled Trial.”</span> <em>Journal of Foot and Ankle Research</em> 6 (1): 40. <a href="https://doi.org/10.1186/1757-1146-6-40">https://doi.org/10.1186/1757-1146-6-40</a>.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./lab1.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">LAB I: Introduction to Jamovi (Part I)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Copyright 2022, Konstantinos I. Bougioukas</div>   
  </div>
</footer>


</body></html>